# https://miniflux.app/docs/installation.html#docker

version: '3.4'
services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "8484:8080"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - RUN_MIGRATIONS=1
      - CLEANUP_ARCHIVE_UNREAD_DAYS=-1
      - CLEANUP_ARCHIVE_READ_DAYS=-1
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    restart: always
